apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  labels:
    app: proxy-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
        - name: proxy-client
          image: demo-proxy-azure-pubsub-proxy-client:local
          imagePullPolicy: IfNotPresent
          env:
            - name: TENANTS
              value: tenant-1,tenant-2,tenant-3
            - name: LOCAL_API_URL
              value: http://local-api:3000
            - name: SERVER_URL
              value: http://proxy-server:8080
            - name: CLIENT_PUBLIC_URL
              value: http://proxy-client:7070
          ports:
            - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  labels:
    app: proxy-client
spec:
  type: ClusterIP
  selector:
    app: proxy-client
  ports:
    - name: http
      port: 7070
      targetPort: 7070
