apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
  labels:
    app: proxy-server
spec:
  # TODO: manual scale after update the secret
  replicas: 0
  selector:
    matchLabels:
      app: proxy-server
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      containers:
        - name: proxy-server
          # Build and push your image with this project contents.
          image: demo-proxy-azure-pubsub-proxy-server:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_URL
              value: "redis://valkey:6379"
            - name: PUBSUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: pubsub-secret
                  key: connectionString
            - name: HUB_NAME
              value: "wawi"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-server
  labels:
    app: proxy-server
spec:
  type: ClusterIP
  selector:
    app: proxy-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
